Search content in emails
DHBW-Mailflow/mailserver pull request #109
Opened 2024-04-16 15:19 UTC by seiferla

2024-04-17 19:11 UTC, jens1o reviewed
just some reformatting changes for now, I see that some functionality isn't fully implemented, yet.

2024-04-17 19:11 UTC, jens1o commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/content/GenericSearchEmailService.java
> +public class GenericSearchEmailService implements SearchEmailUseCase{}
```suggestion
public class GenericSearchEmailService implements SearchEmailUseCase {}
```

2024-04-17 19:11 UTC, jens1o commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/content/SearchContentEmailUseCase.java
> +  List<Email> searchContentInEmails(String content, Address address)throws MailboxSavingException, MailboxLoadingException;
```suggestion
  List<Email> searchContentInEmails(String content, Address address) throws MailboxSavingException, MailboxLoadingException;
```

2024-04-18 10:11 UTC, Jonas-Karl requested changes

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/GenericSearchEmailService.java
> +  }
This functionality should be in the Services which extend the GenericSearchEmailService. I would also suggest renaming it to AbstractSearchEmailSerivce. 

This abstract class could provide functionality like `public boolean containsCaseInsensitive(String emailString, String searchTerm)`. The extending Services could use this functionality while implementing searchEmails on its own

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/GenericSearchEmailService.java
> +  }
```suggestion
  private final ProvideEmailUseCase provideEmailUseCase;

  protected GenericSearchEmailService(ProvideEmailUseCase provideEmailUseCase) {
    this.provideEmailUseCase= provideEmailUseCase;
  }
```
Theoretically you could also use this service here. In this way you dont have to iterate through each mailbox but you can use the provideEmailUseCase.provideEmails() method

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/App.java
Perfect!

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/subject/SearchSubjectEmailService.java
> +public class SearchSubjectEmailService implements SearchSubjectEmailUseCase {
```suggestion
public class SearchSubjectEmailService implements SearchEmailUseCase {
```

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/subject/SearchSubjectEmailService.java
> +  }
```suggestion

```
You dont need this

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/searchemail/subject/SearchSubjectEmailUseCase.java
This interface can be removed

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/cli/BaseCLIPrompt.java
Looks good!

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/cli/usecases/searchemails/SearchEmailTypesCLIPrompt.java
Looks good!

2024-04-18 10:11 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/cli/usecases/searchemails/SearchEmailTypesCLIPrompt.java
> +            this, authUseCase, searchEmails.searchSubjectEmailUseCase()));
You probably also need to add the provideEmailsUseCase

2024-04-18 20:18 UTC, Jonas-Karl approved these changes
Wonderfull

2024-04-18 20:45 UTC, jens1o approved these changes

2024-04-18 20:45 UTC, merged