feat(spam): Allow detecting an e-mail as spam
DHBW-Mailflow/mailserver pull request #129
Opened 2024-04-20 19:06 UTC by jens1o

2024-04-21 18:35 UTC, Jonas-Karl requested changes
This was only a diff review

2024-04-21 18:35 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/spam/strategies/ContentAnalysisSpamDetectionStrategy.java
Should also be in the application or even external layer.

Put it in the external layer when this functionality might be exchanged by another library for spam detection via the email content. Otherwise put it in the application layer

2024-04-21 18:35 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/spam/strategies/ReputationAnalysisSpamDetectionStrategy.java
Should also be in the application or even external layer.

Put it in the external layer when this functionality might be exchanged by another library for spam detection via the sender address. Otherwise put it in the application layer

2024-04-21 22:20 UTC, seiferla reviewed
lgtm

2024-04-22 07:07 UTC, jens1o commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/EmailSendService.java
> +      ruleResult.execute(mailboxRepository, recipient, email);
future-proofing, open-closed principle

2024-04-22 07:09 UTC, jens1o commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/Mailbox.java
> +    }).map(Map.Entry::getKey).toList();
Looking at the existing code, this is the intended and expected behavior. There is no other call to this method where it should contain all of them.

I don't think the name suggests that it is a "all returned e-mails have all the labels"

2024-04-22 07:10 UTC, jens1o commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/result/DeliverIntoFolder.java
> +  public void execute(MailboxRepository mailboxRepository, Address recipient, Email email)
"premature optimization is the root of all evil"

If it matters, we can easily add caching (e.g. LRU-based) to the mailbox repository.

2024-04-22 07:19 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/Mailbox.java
> +    }).map(Map.Entry::getKey).toList();
Ok fine :)

2024-04-22 18:24 UTC, seiferla requested changes

2024-04-22 18:24 UTC, seiferla commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/spam/strategies/ReputationAnalysisSpamDetectionStrategy.java
> +import java.io.File;
remove unused imports

2024-04-22 18:24 UTC, seiferla commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/spam/strategies/ReputationAnalysisSpamDetectionStrategy.java
> +import java.util.stream.Stream;
remove unused imports

2024-04-22 18:24 UTC, seiferla commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/domain/email/mailbox_rules/spam/strategies/UnusualSenderSpamDetectionStrategy.java
> +    return isIPAddress;
i think you can return it directly
return !InternetDomainName.isValid(sender.domain());

2024-04-22 18:24 UTC, seiferla commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/email/parsing/FileMailboxRepository.java
> +import java.util.Arrays;
remove unused import

2024-04-23 13:38 UTC, seiferla approved these changes

2024-04-23 14:13 UTC, Jonas-Karl approved these changes
I changed mainly the following things:
I renamed youre MailboxRuleResults to DeliverServices as they are services to deliver an email to the recipient. 

With this naming, I was able to figure out the correct folders for your files. Services belong to the application layer and the concrete implementations of your strategies belong in the external layer.

I also fixed the tests and I changed the ReputationAnalysisSpamDetectionStrategy to use only INBOX mailboxes and only mailboxes of other accounts. We dont need to search through all inboxes. When an email is in the DELETED or SPAM folder, we do not count it as "not spam sender". I think my thourghts are a bit complicated to explain :D

Overall it was a really good implementation! I did not need to change much👍

2024-04-23 16:06 UTC, merged