Delete emails
DHBW-Mailflow/mailserver pull request #135
Opened 2024-04-26 22:21 UTC by seiferla

2024-04-27 09:27 UTC, jens1o approved these changes
nice work! :)

2024-04-27 10:33 UTC, Jonas-Karl requested changes
Just some small adjustments. I also mentioned one in #134 but due to copy paste, i had to mark this one here too

2024-04-27 10:33 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/organize/delete/DeleteEmailService.java
> +    }
https://github.com/DHBW-Mailflow/mailserver/pull/134#discussion_r1581418081
try adding another method here for easier understanding

2024-04-27 10:33 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/cli/usecases/DeleteEmailsCLIPrompt.java
move this file to a usecases/delete

2024-04-27 10:33 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/external/infrastructure/cli/usecases/DeleteEmailCLIPrompt.java
move this file to a usecases/delete

2024-04-27 10:38 UTC, Jonas-Karl commented
Is it possible to avoid the duplicated code? Why do we need the DeleteEmailsCLIPrompt class, when the functionality is nearly the same as in MarkEmailsCLIPrompt? Maybe renaming the MarkEmailsInterface to OrganizeEmailsUseCase and renaming the method to `organize(Email email)` would avoid the duplicated code. But this is just a guess, I did not try it out

2024-04-28 08:57 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/organize/delete/DeleteEmailService.java
move this into the parent folder

2024-04-28 08:57 UTC, Jonas-Karl commented on src/main/java/de/dhbw/karlsruhe/students/mailflow/core/application/email/organize/delete/DeleteEmailsUseCase.java
move this into the parent folder

2024-04-29 21:26 UTC, Jonas-Karl commented
The duplicated code is fine, because we will use this in our presentation

2024-04-29 22:18 UTC, Jonas-Karl approved these changes
I still need to test it in the IDE but the diff looks good

2024-04-29 23:26 UTC, Jonas-Karl commented
Works fine! You could also filter out the DELETED mailbox, so that we can not deleted a deleted email again. Anyways its not a big issue because nothing crashes. I think this can be merged. Feel free to do it tomorrow :)

2024-04-30 07:47 UTC, merged